package: api_docs
version: '1.1.0'
author: RexDude
supportpage: http://www.redaxo.org/de/forum/
page:
    title: translate:api_docs_title
    perm: admin[]
    pjax: false
    icon: rex-icon fa-book
    subpages:
        docs: { title: 'translate:docs' }
        help:
            title: 'translate:help'
            perm: admin[]
            subpages:
                readme: { title: 'translate:help_readme' }
                changelog: { title: 'translate:help_changelog' }
                license: { title: 'translate:help_license' }
requires:
    redaxo: '^5.0'
